**<h1>Electric Line Extension - Analysis 1**
#### Descriptive Data
<i>Any question regarding the notebook, please contact Robert Ford or Ria Majumder<br>
    Last Updated: 08/13/2025 | Start Development: 08/13/2025</i>
* Utility / IOU Data from PG&E, SDG&E, and SCE for 2023, 2024, and Q1 2025
* Goals: 1. Clean excel files for public downloads.

In [2]:
#Import Libraries and Packages
import pandas as pd
import numpy as np
import matplotlib as plt

In [183]:
pge_2023_df = pd.read_excel("C:/Users/Rford/OneDrive - California Energy Commission/Documents/Analysis - Scripts and Code/Electric-Line-Extension-Data/data/interim/PG&E Data_2023.xlsx", header=1)
sdge_2023_df = pd.read_excel("C:/Users/Rford/OneDrive - California Energy Commission/Documents/Analysis - Scripts and Code/Electric-Line-Extension-Data/data/interim/SDGE Data_2023.xlsx", header=1)
sce_2023_MFNC_df = pd.read_excel("C:/Users/Rford/OneDrive - California Energy Commission/Documents/Analysis - Scripts and Code/Electric-Line-Extension-Data/data/interim/Attachment A - 2024 Final SCE BE Annual Report.xlsx", header=4, sheet_name='Mixed-Fuel New Construction')
sce_2023_AENC_df = pd.read_excel("C:/Users/Rford/OneDrive - California Energy Commission/Documents/Analysis - Scripts and Code/Electric-Line-Extension-Data/data/interim/Attachment A - 2024 Final SCE BE Annual Report.xlsx", header=4, sheet_name='All Electric New Construction')
sce_2023_MFU_df = pd.read_excel("C:/Users/Rford/OneDrive - California Energy Commission/Documents/Analysis - Scripts and Code/Electric-Line-Extension-Data/data/interim/Attachment A - 2024 Final SCE BE Annual Report.xlsx", header=4, sheet_name='Mixed-Fuel Upgrades')
sce_2023_AEU_df = pd.read_excel("C:/Users/Rford/OneDrive - California Energy Commission/Documents/Analysis - Scripts and Code/Electric-Line-Extension-Data/data/interim/Attachment A - 2024 Final SCE BE Annual Report.xlsx", header=4, sheet_name='All Electric Upgrades')

**CLEAN 1**

* For PG&E / SDG&E: Create dataframes for each sector ~ Residential, Nonresidential, and Combination (might include Mixed Use). 
    *   Add a 'Customer Class *' column & group by said column to create dataframe of all sectors
    *   Melt dataframes from wide to long using 'Month' & 'Customer Class *' as the IDs, variable name (columns) as 'type', values as 'counts'
    *   This results in a 624 x 4 dataframe for each IOU
* For SCE: 
    *   Using the individual sheets above, repeat steps for SCE
    *   Skip the summary rows, parse by month into blocks, concat blocks together and drop any repeated headers
    *   Group by 'Customer Class *', melt, and then concat results 
    *   This results in a 528 x 4 dataframe for each SCE sheet

In [ ]:
# Split the DataFrame into three separate DataFrames based on sector: residential, non-residential, and combined ~ drop NaN values
pge_2023_df_res = pge_2023_df.iloc[0:14].dropna(how='all').reset_index(drop=True)
pge_2023_df_nonres = pge_2023_df.iloc[17:31].dropna(how='all').reset_index(drop=True)
pge_2023_df_comb = pge_2023_df.iloc[34:50].dropna(how='all').reset_index(drop=True)
pge_2023_df_res
#pge_2023_df_nonres.reset_index(drop=True)
#pge_2023_df_comb.reset_index(drop=True)

In [ ]:
# Add a 'Customer Class *' column from SCE Annual Report to each sector dataframe
pge_2023_df_res['Customer Class *'] = 'Residential'
pge_2023_df_nonres['Customer Class *'] = 'Nonresidential'
pge_2023_df_comb['Customer Class *'] = 'Combination'

# Combine all three into one dataframe
pge_2023_df_all = pd.concat([pge_2023_df_res, pge_2023_df_nonres, pge_2023_df_comb], ignore_index=True)

# Move 'Customer Class *' to the front if you want
cols = ['Customer Class *'] + [col for col in pge_2023_df_all.columns if col != 'Customer Class *']
pge_2023_df_all = pge_2023_df_all[cols]

pge_2023_df_all

In [ ]:
# Group by 'Customer Class *' and melt each group, then concatenate the results
melted_blocks = []
for name, group in pge_2023_df_all.groupby('Customer Class *'):
    melted = group.melt(id_vars=['Month', 'Customer Class *'], var_name='Type', value_name='Count')
    melted_blocks.append(melted)

sdge_2023_df_all_Melt = pd.concat(melted_blocks, ignore_index=True)
sdge_2023_df_all_Melt

In [ ]:
# Melt the DataFrames to long format
pge_2023_df_recomb = pge_2023_df_comb.melt(id_vars=['Month'], var_name='Type', value_name='Count')
pge_2023_df_renonres = pge_2023_df_nonres.melt(id_vars=['Month'], var_name='Type', value_name='Count')
pge_2023_df_reres = pge_2023_df_res.melt(id_vars=['Month'], var_name='Type', value_name='Count')
pge_2023_df_reres
#pge_2023_df_recomb
#pge_2023_df_renonres

In [ ]:
# Split the DataFrame into three separate DataFrames based on sector: residential, non-residential, and combined ~ drop NaN values
# The sdge_2023_df_comb dataframe is only residential and non-residential, NOT mixed use.
sdge_2023_df_res = sdge_2023_df.iloc[0:14].dropna(how='all').reset_index(drop=True)
sdge_2023_df_nonres = sdge_2023_df.iloc[18:32].dropna(how='all').reset_index(drop=True)
sdge_2023_df_comb = sdge_2023_df.iloc[36:50].dropna(how='all').reset_index(drop=True)
sdge_2023_df_comb

In [ ]:
# Add a 'Customer Class *' column from SCE Annual Report to each sector dataframe
sdge_2023_df_res['Customer Class *'] = 'Residential'
sdge_2023_df_nonres['Customer Class *'] = 'Nonresidential'
sdge_2023_df_comb['Customer Class *'] = 'Combination'

# Combine all three into one dataframe
sdge_2023_df_all = pd.concat([sdge_2023_df_res, sdge_2023_df_nonres, sdge_2023_df_comb], ignore_index=True)

# Move 'Customer Class *' to the front if you want
cols = ['Customer Class *'] + [col for col in sdge_2023_df_all.columns if col != 'Customer Class *']
sdge_2023_df_all = sdge_2023_df_all[cols]

sdge_2023_df_all

In [ ]:
# Group by 'Customer Class *' and melt each group, then concatenate the results
melted_blocks = []
for name, group in sdge_2023_df_all.groupby('Customer Class *'):
    melted = group.melt(id_vars=['Month', 'Customer Class *'], var_name='Type', value_name='Count')
    melted_blocks.append(melted)

sdge_2023_df_all_Melt = pd.concat(melted_blocks, ignore_index=True)
sdge_2023_df_all_Melt

In [184]:
# Prepare each individual sheet in the SCE 2023 data for melting
df = sce_2023_MFNC_df.copy()

monthly_blocks = []
row = 4  # Start after summary

while row < len(df):
    # Get the month label from the first cell of the row
    month_cell = df.iloc[row, 0]
    if pd.isna(month_cell):
        row += 1
        continue  # skip blank rows

    # Try to parse the month label
    try:
        month_label = pd.to_datetime(month_cell).strftime('%b %y')
    except Exception:
        row += 1
        continue  # skip if not a date

    # The next 5 rows are the data for this month (skip the header row)
    data_block = df.iloc[row+1:row+6].copy()
    data_block['Month'] = month_label
    monthly_blocks.append(data_block)

    # Move to the next block (skip the 5 data rows + 1 blank row)
    row += 6

# Combine all blocks
sce_2023_MFNC_clean = pd.concat(monthly_blocks, ignore_index=True)

# Optionally, drop rows where all columns except 'Month' are NaN (in case of trailing blanks)
sce_2023_MFNC_clean = sce_2023_MFNC_clean.dropna(subset=[col for col in sce_2023_MFNC_clean.columns if col != 'Month'], how='all')

# Move 'Month' to the front
cols = ['Month'] + [col for col in sce_2023_MFNC_clean.columns if col != 'Month']
sce_2023_MFNC_clean = sce_2023_MFNC_clean[cols]

# Drop every 5th row to match the expected number of rows
sce_2023_MFNC_clean = sce_2023_MFNC_clean.drop(sce_2023_MFNC_clean.index[::5]).reset_index(drop=True)

sce_2023_MFNC_clean

,Month,Customer Class *,Total Discounts (Non-Exempted Projects),Total Discounts (Exempted projects),Total Allowances (Non-Exempted Projects),Total Allowances (Exempted projects),Total Refund Payments Provided to Builders (Non-Exempted Projects),Total Refund Payments Provided to Builders (Exempted projects),Total Estimated Non-Refundable,Total Estimated Refundable,Total Electric Line Extension Requests Received (Applications),Total Electric Line Extensions Energized,Total Electric Line Extension Applications for Applicant Install
0,Jan 23,Residential,361982.8,0,1250226.91,0,2252901.63,0,467806.72,1912673.28,556,345,32
1,Jan 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
2,Jan 23,Commercial,410316.32,0,2843419.42,0,396422.54,0,652880.76,16427.11,307,159,17
3,Jan 23,Agriculture,9098.22,0,154834.34,0,0,0,1092.75,0,16,10,0
4,Feb 24,Residential,454249.66,0,1080424.47,0,2985830.88,0,550610.99,1591659.09,603,341,11
5,Feb 24,Industrial,0,0,0,0,0,0,0,0,0,0,0
6,Feb 24,Commercial,233258.66,0,2531623.19,0,1329385.67,0,346507.42,0,300,120,11
7,Feb 24,Agriculture,8625.36,0,61999.47,0,1738.36,0,1308.15,0,14,7,0
8,Mar 23,Residential,409785.02,0,1918241.07,0,3864853.56,0,604846.16,1728677.93,693,480,24
9,Mar 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
10,Mar 23,Commercial,314699,0,3455758.67,0,11976.75,0,913906.69,49933.96,392,143,10
11,Mar 23,Agriculture,3208.13,0,29611.85,0,0,0,248,0,19,5,0
12,Apr 23,Residential,317662.32,0,1199026.33,0,2179301.02,0,525647.65,1729410.32,579,373,35
13,Apr 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
14,Apr 23,Commercial,305551.48,0,2583953.95,0,153.95,0,593717.17,5240.34,313,148,11
15,Apr 23,Agriculture,881.12,0,161124.98,0,0,0,2504.8,0,14,14,0
16,May 23,Residential,480060.02,0,1490600.67,0,2376959.79,0,758469.76,2180300.18,667,421,23
17,May 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
18,May 23,Commercial,177350.89,0,4284368.54,0,1008.48,0,426751.66,18373.23,330,160,11
19,May 23,Agriculture,0,0,156049.64,0,0,0,3349.11,5306.58,15,11,0
20,Jun 23,Residential,277623.05,0,1346614.54,0,2700867.55,0,631048.1,1611033.06,684,456,17
21,Jun 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
22,Jun 23,Commercial,126500.19,0,2924557.42,0,98451.3,0,391125.84,49018.85,354,113,4
23,Jun 23,Agriculture,6424.08,0,504279.59,0,0,0,6897.28,0,22,17,0
24,Jul 23,Residential,447596.48,0,1280487.23,0,1648200.85,0,470706.38,1582490.35,661,459,28
25,Jul 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
26,Jul 23,Commercial,372449.01,0,4172981.93,0,410.21,0,572505.23,34440.14,271,154,4
27,Jul 23,Agriculture,6543,0,354578.04,0,0,0,11873.24,0,9,12,0
28,Aug 23,Residential,1082461.57,0,1596064.84,0,1918280.49,0,999100.01,2903874.87,834,517,13
29,Aug 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
30,Aug 23,Commercial,536112.41,0,2192605.91,0,73152.89,0,351474.65,132183.3,382,166,14
31,Aug 23,Agriculture,2009.88,0,373886.7,0,0,0,23808.58,30313.76,23,14,0
32,Sep 23,Residential,920923.88,0,1855632.53,0,1706996.64,0,860325.69,2659169.73,663,460,21
33,Sep 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
34,Sep 23,Commercial,470235.49,0,2649908.27,0,13581.86,0,532795.64,72902.25,304,152,4
35,Sep 23,Agriculture,2602.14,0,394365.41,0,0,0,8904.05,5376.67,12,13,0
36,Oct 23,Residential,1245870.32,0,1542473.01,0,2325323.88,0,1235143.01,5622010.59,666,527,32
37,Oct 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
38,Oct 23,Commercial,155564.67,0,2988578.56,0,724201.63,0,416187.01,6477.17,356,155,6
39,Oct 23,Agriculture,0,0,146077.68,0,40.04,0,272.8,0,10,9,0
40,Nov 23,Residential,691808.77,0,1994651.96,0,2930652.04,0,622221.96,1772712.96,670,471,37
41,Nov 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
42,Nov 23,Commercial,383855.11,0,3643622.56,0,60313.81,0,795214.42,246760.72,314,132,8
43,Nov 23,Agriculture,3859.15,0,87540.06,0,0,0,1451.74,0,13,11,0
44,Dec 23,Residential,874871.51,0,1542814.56,0,2633348.81,0,834067.33,3066904.04,606,532,30
45,Dec 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
46,Dec 23,Commercial,489801.87,0,3500863.85,0,1389915.39,0,520927.3,11335.09,266,163,5
47,Dec 23,Agriculture,3401.78,0,164338.83,0,8273.32,0,0,0,12,11,0

In [185]:
# Group by 'Customer Class *' and melt each group, then concatenate the results
melted_blocks = []
for name, group in sce_2023_MFNC_clean.groupby('Customer Class *'):
    melted = group.melt(id_vars=['Month', 'Customer Class *'], var_name='Type', value_name='Count')
    melted_blocks.append(melted)

sce_2023_MFNC_melted = pd.concat(melted_blocks, ignore_index=True)
sce_2023_MFNC_melted

,Month,Customer Class *,Type,Count
0,Jan 23,Agriculture,Total Discounts (Non-Exempted Projects),9098.22
1,Feb 24,Agriculture,Total Discounts (Non-Exempted Projects),8625.36
2,Mar 23,Agriculture,Total Discounts (Non-Exempted Projects),3208.13
3,Apr 23,Agriculture,Total Discounts (Non-Exempted Projects),881.12
4,May 23,Agriculture,Total Discounts (Non-Exempted Projects),0
...,...,...,...,...
523,Aug 23,Residential,Total Electric Line Extension Applications for...,13
524,Sep 23,Residential,Total Electric Line Extension Applications for...,21
525,Oct 23,Residential,Total Electric Line Extension Applications for...,32
526,Nov 23,Residential,Total Electric Line Extension Applications for...,37
527,Dec 23,Residential,Total Electric Line Extension Applications for...,30

In [186]:
# Prepare each individual sheet in the SCE 2023 data for melting
df2 = sce_2023_AENC_df.copy()

monthly_blocks = []
row = 4  # Start after summary

while row < len(df2):
    # Get the month label from the first cell of the row
    month_cell = df2.iloc[row, 0]
    if pd.isna(month_cell):
        row += 1
        continue  # skip blank rows

    # Try to parse the month label
    try:
        month_label = pd.to_datetime(month_cell).strftime('%b %y')
    except Exception:
        row += 1
        continue  # skip if not a date

    # The next 5 rows are the data for this month (skip the header row)
    data_block = df2.iloc[row+1:row+6].copy()
    data_block['Month'] = month_label
    monthly_blocks.append(data_block)

    # Move to the next block (skip the 5 data rows + 1 blank row)
    row += 6

# Combine all blocks
sce_2023_AENC_clean = pd.concat(monthly_blocks, ignore_index=True)

# Optionally, drop rows where all columns except 'Month' are NaN (in case of trailing blanks)
sce_2023_AENC_clean = sce_2023_AENC_clean.dropna(subset=[col for col in sce_2023_AENC_clean.columns if col != 'Month'], how='all')

# Move 'Month' to the front
cols = ['Month'] + [col for col in sce_2023_AENC_clean.columns if col != 'Month']
sce_2023_AENC_clean = sce_2023_AENC_clean[cols]

# Drop every 5th row to match the expected number of rows
sce_2023_AENC_clean = sce_2023_AENC_clean.drop(sce_2023_AENC_clean.index[::5]).reset_index(drop=True)

sce_2023_AENC_clean

,Month,Customer Class *,Total Discounts (Non-Exempted Projects),Total Discounts (Exempted projects),Total Allowances (Non-Exempted Projects),Total Allowances (Exempted projects),Total Refund Payments Provided to Builders (Non-Exempted Projects),Total Refund Payments Provided to Builders (Exempted projects),Total Estimated Non-Refundable,Total Estimated Refundable,Total Electric Line Extension Requests Received (Applications),Total Electric Line Extensions Energized,Total Electric Line Extension Applications for Applicant Install
0,Jan 23,Residential,65107.43,0,23992.77,0,0,0,24884.58,0,21,9,2
1,Jan 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
2,Jan 23,Commercial,0,0,692106.78,0,0,0,46142.46,1499.97,23,14,0
3,Jan 23,Agriculture,0,0,0,0,0,0,0,0,2,0,0
4,Feb 24,Residential,0,0,20860.32,0,0,0,0,22205.04,23,9,0
5,Feb 24,Industrial,0,0,0,0,0,0,0,0,0,0,0
6,Feb 24,Commercial,0,0,1331354.53,0,0,0,80372.23,0,20,13,0
7,Feb 24,Agriculture,0,0,0,0,0,0,0,0,0,0,0
8,Mar 23,Residential,41286.15,0,60085.18,0,0,0,17435.74,0,38,13,1
9,Mar 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
10,Mar 23,Commercial,0,0,863056.24,0,0,0,55319.48,0,15,20,0
11,Mar 23,Agriculture,0,0,0,0,0,0,0,0,0,0,0
12,Apr 23,Residential,4181.12,0,12739.63,0,0,0,3043.33,0,33,8,0
13,Apr 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
14,Apr 23,Commercial,52768.42,0,918506.3,0,0,0,122646.91,0,12,11,0
15,Apr 23,Agriculture,0,0,0,0,0,0,0,0,4,0,0
16,May 23,Residential,68217.82,0,86136.21,0,0,0,37221.32,0,35,25,0
17,May 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
18,May 23,Commercial,24449.04,0,714292.2,0,0,0,94969.77,0,14,21,0
19,May 23,Agriculture,8783.38,0,699.28,0,0,0,0,0,1,1,0
20,Jun 23,Residential,22361.1,0,41231.59,0,0,0,9060.89,9228.83,39,19,2
21,Jun 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
22,Jun 23,Commercial,27252.6,0,2035540.11,0,0,0,117959.55,6187.83,10,14,0
23,Jun 23,Agriculture,0,0,0,0,0,0,0,0,1,1,0
24,Jul 23,Residential,11967.86,0,45036.3,0,0,0,6012.32,0,31,21,0
25,Jul 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
26,Jul 23,Commercial,22860.08,0,735848.83,0,0,0,121631.9,0,14,16,0
27,Jul 23,Agriculture,0,0,0,0,0,0,0,0,1,1,0
28,Aug 23,Residential,13434.46,0,35271.96,0,0,0,7156.86,0,49,18,1
29,Aug 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
30,Aug 23,Commercial,2426.08,0,673752.77,0,0,0,34634.67,0,10,16,0
31,Aug 23,Agriculture,0,0,0,0,0,0,0,0,0,0,0
32,Sep 23,Residential,44901.37,0,55021.0,0,0,0,27086.35,0,32,21,1
33,Sep 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
34,Sep 23,Commercial,39610.8,0,1490623.56,0,0,0,241428.61,0,6,19,0
35,Sep 23,Agriculture,0,0,569.77,0,0,0,0,0,3,2,0
36,Oct 23,Residential,44443.83,0,63428.16,0,0,0,15352.6,0,40,26,0
37,Oct 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
38,Oct 23,Commercial,32496.16,0,1263833.03,0,0,0,139380.24,0,24,18,0
39,Oct 23,Agriculture,0,0,0,0,0,0,0,0,1,0,0
40,Nov 23,Residential,12276.7,0,50249.1,0,0,0,11737.46,8327.31,21,21,0
41,Nov 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
42,Nov 23,Commercial,92733.2,0,1360496.57,0,0,0,272087.31,0,42,17,0
43,Nov 23,Agriculture,0,0,0,0,0,0,0,0,2,0,0
44,Dec 23,Residential,7275.57,0,34421.32,0,0,0,7207.3,0,18,20,3
45,Dec 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
46,Dec 23,Commercial,122903.99,0,1711206.82,0,31656.63,0,209201.01,0,36,24,0
47,Dec 23,Agriculture,0,0,0,0,0,0,0,0,3,0,0

In [187]:
# Group by 'Customer Class *' and melt each group, then concatenate the results
melted_blocks = []
for name, group in sce_2023_AENC_clean.groupby('Customer Class *'):
    melted = group.melt(id_vars=['Month', 'Customer Class *'], var_name='Type', value_name='Count')
    melted_blocks.append(melted)

sce_2023_AENC_melted = pd.concat(melted_blocks, ignore_index=True)
sce_2023_AENC_melted

,Month,Customer Class *,Type,Count
0,Jan 23,Agriculture,Total Discounts (Non-Exempted Projects),0
1,Feb 24,Agriculture,Total Discounts (Non-Exempted Projects),0
2,Mar 23,Agriculture,Total Discounts (Non-Exempted Projects),0
3,Apr 23,Agriculture,Total Discounts (Non-Exempted Projects),0
4,May 23,Agriculture,Total Discounts (Non-Exempted Projects),8783.38
...,...,...,...,...
523,Aug 23,Residential,Total Electric Line Extension Applications for...,1
524,Sep 23,Residential,Total Electric Line Extension Applications for...,1
525,Oct 23,Residential,Total Electric Line Extension Applications for...,0
526,Nov 23,Residential,Total Electric Line Extension Applications for...,0
527,Dec 23,Residential,Total Electric Line Extension Applications for...,3

In [188]:
# Prepare each individual sheet in the SCE 2023 data for melting
df3 = sce_2023_MFU_df.copy()

monthly_blocks = []
row = 4  # Start after summary

while row < len(df3):
    # Get the month label from the first cell of the row
    month_cell = df3.iloc[row, 0]
    if pd.isna(month_cell):
        row += 1
        continue  # skip blank rows

    # Try to parse the month label
    try:
        month_label = pd.to_datetime(month_cell).strftime('%b %y')
    except Exception:
        row += 1
        continue  # skip if not a date

    # The next 5 rows are the data for this month (skip the header row)
    data_block = df3.iloc[row+1:row+6].copy()
    data_block['Month'] = month_label
    monthly_blocks.append(data_block)

    # Move to the next block (skip the 5 data rows + 1 blank row)
    row += 6

# Combine all blocks
sce_2023_MFU_clean = pd.concat(monthly_blocks, ignore_index=True)

# Optionally, drop rows where all columns except 'Month' are NaN (in case of trailing blanks)
sce_2023_MFU_clean = sce_2023_MFU_clean.dropna(subset=[col for col in sce_2023_MFU_clean.columns if col != 'Month'], how='all')

# Move 'Month' to the front
cols = ['Month'] + [col for col in sce_2023_MFU_clean.columns if col != 'Month']
sce_2023_MFU_clean = sce_2023_MFU_clean[cols]

# Drop every 5th row to match the expected number of rows
sce_2023_MFU_clean = sce_2023_MFU_clean.drop(sce_2023_MFU_clean.index[::5]).reset_index(drop=True)

sce_2023_MFU_clean

,Month,Customer Class *,Total Discounts (Non-Exempted Projects),Total Discounts (Exempted projects),Total Allowances (Non-Exempted Projects),Total Allowances (Exempted projects),Total Refund Payments Provided to Builders (Non-Exempted Projects),Total Refund Payments Provided to Builders (Exempted projects),Total Estimated Non-Refundable,Total Estimated Refundable,Total Electric Line Extension Requests Received (Applications),Total Electric Line Extensions Energized,Total Electric Line Extension Applications for Applicant Install
0,Jan 23,Residential,0,0,288372.5,0,0,0,0,0,816,415,0
1,Jan 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
2,Jan 23,Commercial,0,0,434382.0,0,0,0,0,0,63,28,0
3,Jan 23,Agriculture,0,0,91770.09,0,0,0,0,0,15,9,0
4,Feb 24,Residential,0,0,274458.77,0,0,0,0,0,872,411,0
5,Feb 24,Industrial,0,0,0,0,0,0,0,0,0,0,0
6,Feb 24,Commercial,0,0,646380.56,0,0,0,0,0,72,33,0
7,Feb 24,Agriculture,0,0,281569.33,0,0,0,0,0,18,10,0
8,Mar 23,Residential,0,0,348657.16,0,0,0,0,0,979,519,0
9,Mar 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
10,Mar 23,Commercial,0,0,472413.45,0,0,0,0,0,85,27,0
11,Mar 23,Agriculture,0,0,52246.06,0,0,0,0,0,13,5,0
12,Apr 23,Residential,0,0,318495.81,0,0,0,0,0,826,463,0
13,Apr 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
14,Apr 23,Commercial,0,0,540350.87,0,0,0,0,0,70,33,0
15,Apr 23,Agriculture,0,0,353710.61,0,0,0,0,0,18,12,0
16,May 23,Residential,0,0,367308.34,0,0,0,0,0,885,579,0
17,May 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
18,May 23,Commercial,0,0,746449.77,0,0,0,0,0,92,35,0
19,May 23,Agriculture,0,0,192420.1,0,0,0,0,0,12,11,0
20,Jun 23,Residential,0,0,408381.08,0,0,0,0,0,948,641,0
21,Jun 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
22,Jun 23,Commercial,0,0,410412.67,0,0,0,0,0,108,37,0
23,Jun 23,Agriculture,0,0,292565.72,0,0,0,0,0,13,11,0
24,Jul 23,Residential,0,0,340574.92,0,0,0,0,0,778,503,0
25,Jul 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
26,Jul 23,Commercial,0,0,897171.03,0,0,0,0,0,71,40,0
27,Jul 23,Agriculture,0,0,339759.11,0,0,0,0,0,10,13,0
28,Aug 23,Residential,0,0,330512.77,0,0,0,0,0,956,483,0
29,Aug 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
30,Aug 23,Commercial,0,0,474006.41,0,0,0,0,0,101,31,0
31,Aug 23,Agriculture,0,0,429870.43,0,0,0,0,0,15,8,0
32,Sep 23,Residential,0,0,312227.2,0,0,0,0,0,815,474,0
33,Sep 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
34,Sep 23,Commercial,0,0,540111.26,0,0,0,0,0,71,41,0
35,Sep 23,Agriculture,0,0,87184.09,0,0,0,0,0,13,6,0
36,Oct 23,Residential,0,0,368970.01,0,0,0,0,0,827,538,0
37,Oct 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
38,Oct 23,Commercial,0,0,582150.08,0,0,0,0,0,82,39,0
39,Oct 23,Agriculture,0,0,435646.44,0,0,0,0,0,13,13,0
40,Nov 23,Residential,0,0,352426.77,0,0,0,0,0,710,477,1
41,Nov 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
42,Nov 23,Commercial,0,0,495237.86,0,0,0,0,0,63,41,0
43,Nov 23,Agriculture,0,0,212049.29,0,0,0,0,0,5,11,0
44,Dec 23,Residential,0,0,426532,0,0,0,0,0,695,563,1
45,Dec 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
46,Dec 23,Commercial,0,0,245127.08,0,0,0,0,0,60,34,0
47,Dec 23,Agriculture,0,0,219031.03,0,0,0,0,0,9,8,0

In [189]:
# Group by 'Customer Class *' and melt each group, then concatenate the results
melted_blocks = []
for name, group in sce_2023_MFU_clean.groupby('Customer Class *'):
    melted = group.melt(id_vars=['Month', 'Customer Class *'], var_name='Type', value_name='Count')
    melted_blocks.append(melted)

sce_2023_MFU_melted = pd.concat(melted_blocks, ignore_index=True)
sce_2023_MFU_melted

,Month,Customer Class *,Type,Count
0,Jan 23,Agriculture,Total Discounts (Non-Exempted Projects),0
1,Feb 24,Agriculture,Total Discounts (Non-Exempted Projects),0
2,Mar 23,Agriculture,Total Discounts (Non-Exempted Projects),0
3,Apr 23,Agriculture,Total Discounts (Non-Exempted Projects),0
4,May 23,Agriculture,Total Discounts (Non-Exempted Projects),0
...,...,...,...,...
523,Aug 23,Residential,Total Electric Line Extension Applications for...,0
524,Sep 23,Residential,Total Electric Line Extension Applications for...,0
525,Oct 23,Residential,Total Electric Line Extension Applications for...,0
526,Nov 23,Residential,Total Electric Line Extension Applications for...,1
527,Dec 23,Residential,Total Electric Line Extension Applications for...,1

In [190]:
# Prepare each individual sheet in the SCE 2023 data for melting
df4 = sce_2023_AEU_df.copy()

monthly_blocks = []
row = 4  # Start after summary

while row < len(df4):
    # Get the month label from the first cell of the row
    month_cell = df4.iloc[row, 0]
    if pd.isna(month_cell):
        row += 1
        continue  # skip blank rows

    # Try to parse the month label
    try:
        month_label = pd.to_datetime(month_cell).strftime('%b %y')
    except Exception:
        row += 1
        continue  # skip if not a date

    # The next 5 rows are the data for this month (skip the header row)
    data_block = df4.iloc[row+1:row+6].copy()
    data_block['Month'] = month_label
    monthly_blocks.append(data_block)

    # Move to the next block (skip the 5 data rows + 1 blank row)
    row += 6

# Combine all blocks
sce_2023_AEU_clean = pd.concat(monthly_blocks, ignore_index=True)

# Optionally, drop rows where all columns except 'Month' are NaN (in case of trailing blanks)
sce_2023_AEU_clean = sce_2023_AEU_clean.dropna(subset=[col for col in sce_2023_AEU_clean.columns if col != 'Month'], how='all')

# Move 'Month' to the front
cols = ['Month'] + [col for col in sce_2023_AEU_clean.columns if col != 'Month']
sce_2023_AEU_clean = sce_2023_AEU_clean[cols]

# Drop every 5th row to match the expected number of rows
sce_2023_AEU_clean = sce_2023_AEU_clean.drop(sce_2023_AEU_clean.index[::5]).reset_index(drop=True)

sce_2023_AEU_clean

,Month,Customer Class *,Total Discounts (Non-Exempted Projects),Total Discounts (Exempted projects),Total Allowances (Non-Exempted Projects),Total Allowances (Exempted projects),Total Refund Payments Provided to Builders (Non-Exempted Projects),Total Refund Payments Provided to Builders (Exempted projects),Total Estimated Non-Refundable,Total Estimated Refundable,Total Electric Line Extension Requests Received (Applications),Total Electric Line Extensions Energized,Total Electric Line Extension Applications for Applicant Install
0,Jan 23,Residential,0,0,6485.06,0,0,0,0,0,5,3,0
1,Jan 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
2,Jan 23,Commercial,0,0,128253.7,0,0,0,0,0,0,4,0
3,Jan 23,Agriculture,0,0,0,0,0,0,0,0,0,0,0
4,Feb 24,Residential,0,0,539.61,0,0,0,0,0,3,1,0
5,Feb 24,Industrial,0,0,0,0,0,0,0,0,0,0,0
6,Feb 24,Commercial,0,0,0,0,0,0,0,0,0,0,0
7,Feb 24,Agriculture,0,0,0,0,0,0,0,0,0,0,0
8,Mar 23,Residential,0,0,4434.74,0,0,0,0,0,7,4,0
9,Mar 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
10,Mar 23,Commercial,0,0,142035.91,0,0,0,0,0,0,5,0
11,Mar 23,Agriculture,0,0,0,0,0,0,0,0,0,0,0
12,Apr 23,Residential,0,0,11209.25,0,0,0,0,0,8,3,0
13,Apr 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
14,Apr 23,Commercial,0,0,0,0,0,0,0,0,2,0,0
15,Apr 23,Agriculture,0,0,0,0,0,0,0,0,1,0,0
16,May 23,Residential,0,0,6930.03,0,0,0,0,0,3,4,0
17,May 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
18,May 23,Commercial,0,0,1665.53,0,0,0,0,0,1,2,0
19,May 23,Agriculture,0,0,0,0,0,0,0,0,0,0,0
20,Jun 23,Residential,0,0,7968.36,0,0,0,0,0,6,4,0
21,Jun 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
22,Jun 23,Commercial,0,0,2887.6,0,0,0,0,0,0,1,0
23,Jun 23,Agriculture,0,0,0,0,0,0,0,0,0,0,0
24,Jul 23,Residential,0,0,5149.01,0,0,0,0,0,5,5,0
25,Jul 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
26,Jul 23,Commercial,0,0,4227.62,0,0,0,0,0,0,1,0
27,Jul 23,Agriculture,0,0,0,0,0,0,0,0,1,0,0
28,Aug 23,Residential,0,0,4676.24,0,0,0,0,0,7,7,0
29,Aug 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
30,Aug 23,Commercial,0,0,136316.77,0,0,0,0,0,2,2,0
31,Aug 23,Agriculture,0,0,0,0,0,0,0,0,0,0,0
32,Sep 23,Residential,0,0,584.59,0,0,0,0,0,8,3,0
33,Sep 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
34,Sep 23,Commercial,0,0,5980.74,0,0,0,0,0,0,1,0
35,Sep 23,Agriculture,0,0,0,0,0,0,0,0,0,0,0
36,Oct 23,Residential,0,0,652.49,0,0,0,0,0,3,2,0
37,Oct 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
38,Oct 23,Commercial,0,0,0,0,0,0,0,0,1,0,0
39,Oct 23,Agriculture,0,0,0,0,0,0,0,0,1,0,0
40,Nov 23,Residential,0,0,4895.31,0,0,0,0,0,0,5,0
41,Nov 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
42,Nov 23,Commercial,0,0,0,0,0,0,0,0,0,0,0
43,Nov 23,Agriculture,0,0,0,0,0,0,0,0,3,0,0
44,Dec 23,Residential,0,0,7247.21,0,0,0,0,0,1,9,0
45,Dec 23,Industrial,0,0,0,0,0,0,0,0,0,0,0
46,Dec 23,Commercial,0,0,34822.52,0,0,0,0,0,2,3,0
47,Dec 23,Agriculture,0,0,0,0,0,0,0,0,5,0,0

In [191]:
# Group by 'Customer Class *' and melt each group, then concatenate the results
melted_blocks = []
for name, group in sce_2023_AEU_clean.groupby('Customer Class *'):
    melted = group.melt(id_vars=['Month', 'Customer Class *'], var_name='Type', value_name='Count')
    melted_blocks.append(melted)

sce_2023_AEU_melted = pd.concat(melted_blocks, ignore_index=True)
sce_2023_AEU_melted

,Month,Customer Class *,Type,Count
0,Jan 23,Agriculture,Total Discounts (Non-Exempted Projects),0
1,Feb 24,Agriculture,Total Discounts (Non-Exempted Projects),0
2,Mar 23,Agriculture,Total Discounts (Non-Exempted Projects),0
3,Apr 23,Agriculture,Total Discounts (Non-Exempted Projects),0
4,May 23,Agriculture,Total Discounts (Non-Exempted Projects),0
...,...,...,...,...
523,Aug 23,Residential,Total Electric Line Extension Applications for...,0
524,Sep 23,Residential,Total Electric Line Extension Applications for...,0
525,Oct 23,Residential,Total Electric Line Extension Applications for...,0
526,Nov 23,Residential,Total Electric Line Extension Applications for...,0
527,Dec 23,Residential,Total Electric Line Extension Applications for...,0